### PR TITLE
Palo Alto test update. MERGE IN MASTER FIRST

### PR DESCRIPTION
**Pull request by justinleet**
## Contributor Comments
The vast majority of these commits should fall out, once master is merged into this.  Let me know if they don't, and I'll reopen.
See https://github.com/ctramnitz/metron/commit/bf8ce62cb5ed3846f288e4a7a606410ebbaf9d30 for the relevant commit.

### CODE REVIEW

**Comment by ctramnitz** [comment]
@justinleet , my git foo may be a bit off or I missed a step. But after merging in master, there is still a bunch of changes. Any suggestion how to proceed?

**Comment by ctramnitz** [comment]
@justinleet as you can see, I gave it a shot and it merged cleanly.

However, I'm not sure the result for is really as expected.
It shouldn't be "<11>Jan  5 05:38:59 PAN1.exampleCustomer.com 1", but just "1". The rest is the Syslog header.

Is the PaloParser called against the entire syslog line or after the header has been stripped out?

**Comment by justinleet** [comment]
@ctramnitz I'll dig in and take a look.  I'm honestly not sure, since I haven't really dealt with this much lately.

**Comment by justinleet** [comment]
@ctramnitz I'm going to move this discussion over to the main PR to get it a little more visibility

**Pull request merged**
